### ISSUE TITLE
[bug] Realm and Options handling for ad strategy connections

### ISSUE THREAD

**Issue by rdark** [yieldr/terraform-provider-auth0#30]
Possibly two separate issues here, let me know if you want me to split. Only had an hour this morning to start troubleshooting, but just wanted to get something up to show where I was at with it.

1. Realms: AD connection strategies are a bit odd in the auth0 API; they have an implicit realm named after the connection, but you cannot set this or modify it. It seems in the current version on master, attempting to use a previously working configuration for 0.1.0, that omits a `realm`, now breaks, resulting in `400 Bad Request: Realms is only supported for database connections`.

2. Options. This issue was previously existing. The only way to create an ad strategy connection was to _not_ set options at creation time, and then set it to an empty map afterwards.

Example in terraform code (works first time, dirty/failing plan after).

```provider "auth0" {}
 resource "auth0_connection" "my_ad_connection" {
	name = "Acceptance-Test-Ad-Connection"
	strategy = "ad"
}
```

#29 illustrates the current behaviour

**Comment by alexkappa** [comment]
Hi @rdark I am afraid we this relates to the (mis)handling of zero values from Go structs. This means a property that is set to a "zero" value (i.e. `0`, `false`, `""`) will be omitted from the json output. 

To address this, I've changed the yieldr/go-auth0 library to use pointers instead. Making any non nil pointer serializable by json.

I plan to merge this in as soon as possible, but since it introduces backwards incompatible changes we need to be wary of code that we might brake.

**Comment by rdark** [comment]
Awesome. Thanks @alexkappa!

**Comment by alexkappa** [comment]
This issue is addressed in the latest releases. Please give it a try and let me know :)

**Comment by rdark** [comment]
Thanks so much @alexkappa. Can confirm that specific issue 1 above is fixed in this release.
